import React from 'react'
import "./Terms.css"
import Footer from '../Footer'
import Newsletter from '../Newsletter'
import Navbar from "../Navbar"
import TermsCard from './TermsCard'
import TermsUse from './TermsUse'
import TermsCardTwo from './TermsCardTwo'

function Terms() {
  return (      
    <>
      <Navbar />
      <div className='termsC'>
        <h2>Terms and Conditions</h2>
        <h4>By signing up for, or using the Juciparo services or its affiliates, you are agreeing to be bound by the following terms and conditions. The services offered by Juciparo under the Terms of Service include various products and services to help you sell goods and services to buyers, whether Online or Offline.</h4>
        <div className='term--top'>
            <TermsCard 
                head = "Customer Service"
                text = "This document is an electronic record in terms of National Information Technology Development Agency Act, 2007 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the National Information Technology Development Agency Act, 2007. This electronic record is generated by a computer system and does not require any physical or digital signatures. Your use of the Juciparo website,  and tools are governed by the following terms and conditions as applicable to the website. If you transact on Juciparo website, you shall be subject to the policies that are applicable to the website for such transaction. For the purpose of these terms of use, wherever the context so require, ‘You’ shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data while registering on the Website as a Registered User. When you use any of the services provided by on our website, including but not limited to, (e.g., Customer Reviews), you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. Juciparo website reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time."
            />
            <TermsCard 
                head = "Membership Eligibility"
                text = "Use of the Juciparo Website is available only to persons who can form legally binding contracts under Nigerian governing laws. If you are a minor i.e. under the age of 18 years, you shall not register as a member of Juciparo website and shall not transact or use Juciparo website. As a minor if you wish to use or transact on Juciparo website, such use or transaction may be made by your legal guardian or parents who have registered as users of Juciparo website. Our website reserves the right to terminate your membership and refuse to provide you with access to Juciparo website if it is brought to Juciparo notice or if it is discovered that you are under the age of 18 years."
            />
            <TermsCard 
                head = "Your Account and Registration Obligations"
                text = "If you use Juciparo website, you shall be responsible for maintaining the confidentiality of your User ID and Password and you shall be responsible for all activities that occur under your User ID and Password. You agree that if you provide any information that is untrue, inaccurate, not current or incomplete that Juciparo has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, Juciparo has the right to indefinitely suspend or terminate or block access of your membership with Juciparo and refuse to provide you with access to the Website."
            />
            <TermsCard 
                head = "Communications"
                text = "When You use the Website or send emails or other data, information or communication to Juciparo website, You agree and understand that You are communicating with Juciparo through electronic records and You consent to receive communications via electronic records from Juciparo website periodically. Juciparo may communicate with You by email or by such other mode of communication, electronic or otherwise."
            />
            
        </div>

        <div className='termsUse--section'>
          <TermsUse />
        </div>
        
        <div className='middle'>
          <TermsCardTwo
                  head = "Contents Posted on Site"
                  text = "All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, “Content”), including but not limited to the design, structure, selection, coordination, expression, “look and feel” and arrangement of such Content,contained on Juciparo website is owned,controlled or licensed by or to Juciparo, and is protected by trade dress, copyright, patent and trademark laws, and various other intellectual property rights and unfair competition laws. Except as expressly provided in these Terms of Use, no part of Juciparo website  and no Content may be copied,reproduced,re-published,uploaded,posted,publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise,without Juciparo’s express prior written consent."
          />
          <TermsCardTwo
                  head = "Other Businesses"
                  text = "Juciparo does not take responsibility or liability for the actions, products, content and services on Juciparo website, which are linked to Affiliates and / or third party websites using Juciparo website APIs or otherwise. In addition, Juciparo website may provide links to the third party websites of affiliated companies and certain other businesses for which, Juciparo assumes no responsibility for examining or evaluating the products and services offered by them, and Juciparo does not warrant the offerings of, any of these businesses or individuals or the content of such third party website(s). Juciparo does not in any way endorse any third party website(s) or content thereof."
          />
          <TermsCardTwo
                  head = "Links"
                  text = "Juciparo website welcomes links to this site. You may establish a hypertext link to Juciparo website, provided that the link does not state or imply any sponsorship or endorsement of your site by Juciparo website. You must not use on your site or in any other manner any trademarks, service marks or any other materials appearing on Juciparo website, including any logos or characters, without the express written consent of Juciparo website and the owner of the mark or materials. You must not frame or otherwise incorporate into another third party website or present in conjunction with or juxtaposed against such a website any of the content or other materials on the Juciparo website website without Juciparo’s prior written consent."
          />
        </div>
      </div>
      <Newsletter />
      <Footer />
    </>
  )
}

export default Terms


